### ISSUE TITLE
Travis doesn't build with the scala maven plugin of the ETS - maven version is too old.

### ISSUE THREAD

**Issue by ghost** [Galeria-Kaufhof/ets-locking#5]
https://github.com/travis-ci/travis-ci/issues/9366

We need to add a mvnw wrapper script to use the newest mvn version on travis.

**Comment by maphi** [comment]
What about the solutions provided in https://github.com/travis-ci/enterprise-installation/issues/14

**Comment by ghost** [comment]
Merged to the wrong branch (master) instead of 0.x.x - not a problem in this case because 0.x.x has not been diverged from master yet and I fixed the 0.x.x branch...
